package com.business.data.controller;

import com.smallchill.core.base.controller.CurdController;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import com.business.data.model.Order;

/**
 * Generated by Blade.
 * 2017-08-31 10:23:42
 */
@Controller
@RequestMapping("/order")
public class OrderController extends CurdController<Order> {


    @Override
    public String controllerKey() {
        return "order";
    }

}
