package com.ysisl.model;


import com.smallchill.core.base.model.DataModel;
import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.base.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-07-12 23:32:18
 */
@Table(name = "ysisl_account")
@SuppressWarnings("serial")
public class Account extends BaseModel {

    private Integer deptId; //所属部门
    private String address; //地址
    private String name; //客户名称
    private String phone; //电话号码
    private String sex; //性别


    public Integer getDeptId() {
        return deptId;
    }

    public void setDeptId(Integer deptd) {
        this.deptId = deptId;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }


}
