/**
 * @Description:TODO
 * @author:HuangLJ
 * @time:2017年8月2日 上午9:45:08
 */
package com.business.recommend.model;

import com.alibaba.fastjson.annotation.JSONField;


import java.util.Date;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.base.model.BaseModel;

/**
 * Generated by ysisl.
 * 2017-08-05 10:31:57
 */
@Table(name = "rec_action")
@SuppressWarnings("serial")
public class Action extends BaseModel {

    private String md5;            //md5(bid&request_id&TOKEN)
    private String requestId; //request_id 为“毫秒级时间戳随机数”
    private String dataType;    //1：item，2：action
    private String bid;            //腾讯云为该业务分配的业务标识
    private String uidType;    //0：QQ，1：微信号，3：设备号imei/idfa或其md5值（默认），4：手机号
    private String uid;                //QQ，微信号，imei/idfa或其md5值，手机号
    private String itemId;        //物料标识
    private String sceneId;    //广告展示场景。
    private String actionType;    //行为类型。1：曝光（浏览）,2：点击（播放）,3：转化（购买）,4：点赞
    private String source;            //流量标记。tx：腾讯流量, bus：业务流量, def：默认流量
    private String traceId;        //跟踪点击和曝光的自定义跟踪id
    private String actionTime;    //行为发生秒级时间戳（默认当前时间）
    private Double latitude;
    private Double longitude;
    private String country;
    private String city;
    private String key1;
    private String key2;
    private String key3;
    private String key4;
    private String syncCode;
    private String syncMsg;


    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public String getBid() {
        return bid;
    }

    public void setBid(String bid) {
        this.bid = bid;
    }

    public String getUidType() {
        return uidType;
    }

    public void setUidType(String uidType) {
        this.uidType = uidType;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getItemId() {
        return itemId;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    public String getSceneId() {
        return sceneId;
    }

    public void setSceneId(String sceneId) {
        this.sceneId = sceneId;
    }

    public String getActionType() {
        return actionType;
    }

    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public String getActionTime() {
        return actionTime;
    }

    public void setActionTime(String actionTime) {
        this.actionTime = actionTime;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getKey1() {
        return key1;
    }

    public void setKey1(String key1) {
        this.key1 = key1;
    }

    public String getKey2() {
        return key2;
    }

    public void setKey2(String key2) {
        this.key2 = key2;
    }

    public String getKey3() {
        return key3;
    }

    public void setKey3(String key3) {
        this.key3 = key3;
    }

    public String getKey4() {
        return key4;
    }

    public void setKey4(String key4) {
        this.key4 = key4;
    }

    public String getSyncCode() {
        return syncCode;
    }

    public void setSyncCode(String syncCode) {
        this.syncCode = syncCode;
    }

    public String getSyncMsg() {
        return syncMsg;
    }

    public void setSyncMsg(String syncMsg) {
        this.syncMsg = syncMsg;
    }
}
