package com.business.recommend.model;


import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.base.model.BaseModel;

/**
 * Generated by ysisl.
 * 2017-08-05 10:31:57
 */
@Table(name = "rec_response")
@SuppressWarnings("serial")
public class ResponseItem extends BaseModel {

    private String itemId;
    private String Weight;
    private String itemName;
    private String requestId;

    public String getItemId() {
        return itemId;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    public String getWeight() {
        return Weight;
    }

    public void setWeight(String Weight) {
        this.Weight = Weight;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }
}
