package com.business.ysisl.controller;


import com.smallchill.core.base.controller.CurdController;
import com.business.ysisl.model.Account;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Generated by Blade.
 * 2017-07-12 23:32:18
 */
@Controller
@RequestMapping("/account")
public class AccountController extends CurdController<Account> {

    @Override
    public String controllerKey() {
        return "account";
    }
}
