package com.business.recommend.controller;

import com.business.recommend.model.Item;
import com.business.recommend.service.TecentUpload;
import com.business.recommend.util.CommonUtil;
import com.smallchill.core.annotation.Json;
import com.smallchill.core.base.controller.CurdController;
import com.smallchill.core.plugins.dao.Blade;
import com.smallchill.core.toolbox.CMap;
import com.smallchill.core.toolbox.ajax.AjaxResult;
import com.smallchill.core.toolbox.support.Convert;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import com.business.recommend.model.Action;

import javax.annotation.Resource;
import java.util.List;

/**
 * Generated by Blade.
 * 2017-08-05 10:31:57
 */
@Controller
@RequestMapping("/action")
public class ActionController extends CurdController<Action> {

    @Resource
    private TecentUpload tecentUpload;

    @Override
    public String controllerKey() {
        return "action";
    }

    @Json
    @RequestMapping("/init")
    public AjaxResult init() {


        Action action = new Action();
        action.setMd5("testmd5");
        action.setRequestId(String.valueOf(System.currentTimeMillis()));
        action.setDataType("2");
        action.setBid("b_teg_openrecom_ujwu65iquql72ugizntl");
        action.setUidType("0");
        action.setUid("549747095");
        action.setItemId("W-97I8V");
        action.setSceneId("20000244");
        action.setActionType("2");
        action.setSource("tx");
        action.setTraceId(String.valueOf(System.currentTimeMillis()));
        action.setActionTime(CommonUtil.get10DateStr());

        action.setLongitude(130.123);
        action.setLatitude(35.23);
        action.setCountry("China");
        action.setCity("广州");

        if (service.save(this, action, Action.class, null))
            return success(SAVE_SUCCESS_MSG);
        else
            return error(SAVE_FAIL_MSG);


    }

    @Json
    @RequestMapping("/upload")
    public AjaxResult upload() {
        String ids = getParameter("ids");
        List<Action> list = Blade.create(Action.class).findBy("id in (#{join(ids)})", CMap.init().set("ids", Convert.toIntArray(ids)));
        boolean success = true;
        for (Action action : list) {
            Action actionRes = tecentUpload.actionUpload(action);
            if (!actionRes.getSyncCode().equals("0"))
                success = false;
        }
        if (success)
            return success("全部上传成功");
        else
            return error("部分记录上传失败，详细信息查看说明");

    }
}
