package com.business.recommend.controller;

import com.business.recommend.service.ResponseItemIntercept;
import com.smallchill.core.annotation.Json;
import com.smallchill.core.base.controller.CurdController;
import com.smallchill.core.meta.MetaIntercept;
import com.smallchill.core.toolbox.kit.StrKit;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import com.business.recommend.model.ResponseItem;

/**
 * Generated by Blade.
 * 2017-08-05 10:31:57
 */
@Controller
@RequestMapping("/responseItem")
public class ResponseItemController extends CurdController<ResponseItem> {


    @Override
    public String controllerKey() {
        return "responseItem";
    }

    @Override
    public MetaIntercept intercept() {
        return new ResponseItemIntercept();
    }


}
