package com.business.recommend.controller;

import com.business.recommend.model.Item;
import com.business.recommend.service.TecentUpload;
import com.smallchill.core.annotation.Json;
import com.smallchill.core.base.controller.CurdController;
import com.smallchill.core.plugins.dao.Blade;
import com.smallchill.core.toolbox.CMap;
import com.smallchill.core.toolbox.ajax.AjaxResult;
import com.smallchill.core.toolbox.support.Convert;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import com.business.recommend.model.SuggestRequest;

import javax.annotation.Resource;
import java.util.List;

/**
 * Generated by Blade.
 * 2017-08-05 10:31:57
 */
@Controller
@RequestMapping("/suggestRequest")
public class SuggestRequestController extends CurdController<SuggestRequest> {


    @Resource
    private TecentUpload tecentUpload;

    @Override
    public String controllerKey() {
        return "suggestRequest";
    }

    @Json
    @RequestMapping("/init")
    public AjaxResult init() {

        SuggestRequest SuggestRequest = new SuggestRequest();
        SuggestRequest.setMd5("testmd5");
        SuggestRequest.setService_type("3");
        SuggestRequest.setRequestId(String.valueOf(System.currentTimeMillis()));
        SuggestRequest.setBid("b_teg_openrecom_ujwu65iquql72ugizntl");
        SuggestRequest.setUidType("0");
        SuggestRequest.setUid("549747095");
        SuggestRequest.setSceneId("20000244");
        SuggestRequest.setRequestNum("50");
        SuggestRequest.setPoolId("poolId1");
        SuggestRequest.setCid("W-97CW4");

        SuggestRequest.setLongitude(130.123);
        SuggestRequest.setLatitude(35.23);
        SuggestRequest.setCountry("China");
        SuggestRequest.setCity("广州");

        if (service.save(this, SuggestRequest, SuggestRequest.class, null))
            return success(SAVE_SUCCESS_MSG);
        else
            return error(SAVE_FAIL_MSG);

    }


    @Json
    @RequestMapping("/getsr")
    public AjaxResult upload() {
        String ids = getParameter("ids");
        List<SuggestRequest> list = Blade.create(SuggestRequest.class).findBy("id in (#{join(ids)})", CMap.init().set("ids", Convert.toIntArray(ids)));
        boolean success = true;
        for (SuggestRequest sr : list) {
            SuggestRequest srRes = tecentUpload.srGet(sr);
            if (!srRes.getSyncCode().equals("0"))
                success = false;
        }
        if (success)
            return success("全部请求成功，请查看明细产品推荐");
        else
            return error("部分记录请求失败，详细信息查看说明");

    }


}
