package com.business.data.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-08-31 10:23:42
 */
@Table(name = "df_orders")
@SuppressWarnings("serial")
public class Order extends BaseModel {

    private String city; //城市
    private String phone; //手机号
    private String productId; //购买产品
    private String unionId; //外部Key
    private Date orderDate; //订单时间
    private Date registDate; //注册时间

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getUnionId() {
        return unionId;
    }

    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Date getRegistDate() {
        return registDate;
    }

    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }


}
