package com.business.data.service.impl;

import java.util.Map;

import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;
import com.smallchill.core.plugins.dao.Md;
import com.smallchill.core.toolbox.CMap;
import com.smallchill.core.toolbox.support.Convert;
import com.business.data.model.Order;
import com.business.data.service.OrderService;

/**
 * Generated by Blade.
 * 2017-08-31 10:23:42
 */
@Service
public class OrderServiceImpl extends BaseService<Order> implements OrderService {

    @Override
    public boolean updateStatus(String ids, Integer status) {
        CMap map = CMap.init().set("status", status).set("ids", Convert.toIntArray(ids));
        boolean temp = updateBy("status = #{status}", "id in (#{join(ids)})", map);
        return temp;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Map<String, Object> findOne(Object id) {
        return Md.selectOne("order.findOne", CMap.init().set("id", id), Map.class);
    }

}
