package com.business.data.service;

import java.util.Map;

import com.smallchill.core.base.service.IService;
import com.business.data.model.Order;

/**
 * Generated by Blade.
 * 2017-08-31 10:23:42
 */
public interface OrderService extends IService<Order> {

    boolean updateStatus(String ids, Integer status);

    Map<String, Object> findOne(Object id);

}
